### ISSUE TITLE
Apologies for making this issue

### ISSUE THREAD

**Issue by PonyWarrior** [drakray/drakraysdecostuff#1]
However I have no other means of contacting you. In this [issue](https://github.com/Lothrazar/RootsClassic/issues/99) you mentioned having compiled a version of Roots Classic that loads on the current Forge version, could you please send it to me?

I have been unable to compile the mod myself due to errors, and am truly desperate to get the mod working in ATM9.

Once again, apologies for contacting you this way.

**Comment by drakray** [comment]
No problem ;)

To be clear, I didn't recompile the mod, I just went in the jar file(opened with 7-zip) and modified the mods.toml in the META-INF folder(extract the file, modified versionRange to versionRange="[47,]", put the file back in the jar overwriting the other)
It is less than ideal, but work for a local play
It is not a solution for a modPack, since the jar is modified, so it will be overwritten by the curseforge launcher or whatever
And again, I have yet to really dig into the mod in a Neoforge environment, so I'm not even certain that it is stable, I just know that it load

If you just want to add it to your instance, without connecting to any server you should  be fine, but that's about it

**Comment by PonyWarrior** [comment]
Thanks a lot for replying, your method worked perfectly. I was able to put the mod on my server and my client, now I can make my acceleration staff again.

![Screenshot 2023-12-07 174304](https://github.com/drakray/drakraysdecostuff/assets/22421356/8950b7b3-4f73-4d0c-83ea-5c211a0efe26)

**Comment by drakray** [comment]
Nothing like adding a (somewhat) large mod for a single feature XD
